### ISSUE TITLE
How To Recompile

### ISSUE THREAD

**Issue by roughnecks** [GMMan/SteamNotificationsTray#1]
Hi there,
can you post/link a guide to recompile your software? I never did that and would like to try.

Thanks

**Comment by GMMan** [comment]
Install [Visual Studio](https://www.visualstudio.com/products/visual-studio-community-vs) or [MonoDevelop](http://www.monodevelop.com), load up the solution, and build.

**Comment by roughnecks** [comment]
Thanks. I installed Visual Studio, loaded solution and started building. I got 2 warnings and 2 errors.

## WARNING 1)

Severity    Code    Description Project File    Line    Suppression State
Warning     The referenced component 'System.Net.Http' could not be found.  SteamNotificationsTray          

## WARNING 2)

Severity    Code    Description Project File    Line    Suppression State
Warning     Could not resolve this reference. Could not locate the assembly "System.Net.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.   SteamNotificationsTray          

## ERROR 1)

Severity    Code    Description Project File    Line    Suppression State
Error   CS0234  The type or namespace name 'Http' does not exist in the namespace 'System.Net' (are you missing an assembly reference?) SteamNotificationsTray  C:\Users\roughnecks\Downloads\SteamNotificationsTray-1.1.1.0\SteamNotificationsTray\WebLogin\SteamWebLogin.cs   7   Active

## ERROR 2)

Severity    Code    Description Project File    Line    Suppression State
Error   CS0234  The type or namespace name 'Http' does not exist in the namespace 'System.Net' (are you missing an assembly reference?) SteamNotificationsTray  C:\Users\roughnecks\Downloads\SteamNotificationsTray-1.1.1.0\SteamNotificationsTray\NotificationsClient.cs  7   Active

---

I honestly have no clues about those missing assembly references, so I need a bit of help.

**Comment by GMMan** [comment]
Make sure you have .NET Framework 4.5.1 installed.

**Comment by roughnecks** [comment]
I'm running Windows 10 Home x64 Italian and it's fully updated.

![framework](https://cloud.githubusercontent.com/assets/1666536/18757315/b146f416-80f3-11e6-86fe-851dab96c180.PNG)

**Comment by GMMan** [comment]
Looks like I accidentally targeted ASP.NET's System.Net.Http assembly. Pull changes and you should be able to compile it properly.

**Comment by roughnecks** [comment]
It worked, thanks 👍
