### ISSUE TITLE
Credentials Expiration/Loss

### ISSUE THREAD

**Issue by roughnecks** [GMMan/SteamNotificationsTray#10]
Hello.

I'm wondering why sometimes SteamNotificationsTray is losing my credentials, i.e. I have to login again.
This is not happening with other Steam-related applications I'm using, like ASF, bitlbee-steam and the Steam official client itself, of course.

Thanks

**Comment by GMMan** [comment]
This was covered in #3.

**Comment by roughnecks** [comment]
My bad, didn't remember about that.
Anyhow it's still weird because I shut down my PC yesterday, SNT was logged in and working... Today, as soon as I logged in Windows and SNT auto started, it was no longer connected (and Steam Community was up, AFAIK).
