### ISSUE TITLE
Settings - Items: Not Onored

### ISSUE THREAD

**Issue by roughnecks** [GMMan/SteamNotificationsTray#11]
Hi there.

I wanted to exclude "Comments" notifications so I unchecked it in "Settings - Items" but the program is still notifying me via balloons.

**Comment by GMMan** [comment]
That setting only controls whether the item is shown in the menu when there aren't any new items of the type.

**Comment by roughnecks** [comment]
OK, so the balloons always show? Could you make that a new feature maybe?

Don't know if I understood you correctly, but it's showing me Items (Comments in this case) in the menu too, even when I uncheck it.

**Comment by GMMan** [comment]
The balloon will currently always show the diff between the current and previous checks. If you have any items that have a non-zero count, they will also show on the menu.

**Comment by roughnecks** [comment]
Sorry but it doesn't make much sense to me. We got a specific option for balloons, make the Items settings so that it shows when checked and doesn't show if not... It just looks easier to me this way.

**Comment by GMMan** [comment]
The hint text for the items tab says "always show the following items", not "only show the following items". It's designed to behave just like the notifications list in the Steam client, but allowing you to choose which items are always visible. I can add an "always hide" option, but it may be a while before I get to it.

**Comment by roughnecks** [comment]
Alright, I'm an happy user already, would be great if you could do that too.
I'm closing this one, have a nice week.
