### ISSUE TITLE
Chrome freezes when opening notifications (Fall Creators Update)

### ISSUE THREAD

**Issue by roughnecks** [GMMan/SteamNotificationsTray#14]
Hello.

I'm not sure if it's just me or not but since I've upgraded Windows to the FCU, chrome freezes whenever I click SteamNotificationTray Balloons. As soon as the new tab opens, the browser becomes unresponsive and the only way to restore it is killing its process from the Task Manager.

**Comment by GMMan** [comment]
Would you mind trying the option to open pages in Steam?

**Comment by roughnecks** [comment]
Sure. Set it, but I'll have to wait for some notification. Will let you know.

**Comment by roughnecks** [comment]
It's working with Steam.

**Comment by GMMan** [comment]
I imagine it's an issue with Chrome. Any freezes when other programs try to open web pages in browser?

**Comment by roughnecks** [comment]
Wait a sec. I'm able to browse Steam Store and Community from Chrome just fine, it freezes only when clicking on SNT's balloons. As per your question, do you mean like open a link from Mail Client and such? No problems there.

**Comment by GMMan** [comment]
Not really sure what the issue could be. I'm just using the standard ShellExecute call to open the page. Unfortunately, I don't have FCU, so can't debug this right now.

**Comment by roughnecks** [comment]
I'm noticing another issue. When opening notifications in Steam Client it works but Steam Icon in Application Bar starts flashing as if the window wasn't in foreground. I have to click somewhere on Steam to make it stop.

**Comment by roughnecks** [comment]
I don't know, maybe something broke for me during the upgrade... I tested it with Edge and Firefox too and they work fine.

**Comment by roughnecks** [comment]
Forgot to update this one, it fixed by itself somehow.
