### ISSUE TITLE
Color of number (notifications)

### ISSUE THREAD

**Issue by roughnecks** [GMMan/SteamNotificationsTray#2]
Hello,
would it be possible to have the color of numbers in black (or a color picker for it too)?
I changed my notifications color to amber and the white number is barely visible.

Thanks

**Comment by GMMan** [comment]
This has been implemented as of b5fb8d56aaf6ac166cdb4d746d32dd5fb941081b

Note the envelope color doesn't change, because it's a bitmap and I don't really want to complicate things.
