### ISSUE TITLE
Credentials loss

### ISSUE THREAD

**Issue by roughnecks** [GMMan/SteamNotificationsTray#3]
Hi there,
Steam community is currently down and has been for the latest hours. I closed the tray and opened it again 1 hour ago but it asked for my credentials once again. Why? Other services like bitlbee-steam haven't got this issue.

On a side note, SteamNotificationsTray is still unable to login because it can't connect to steamcommunity, or so it says. Again, why? I know community is down but you can still login to Steam just fine right now, either with the official client, browser and other third-party apps, except yours.

Thanks

**Comment by GMMan** [comment]
The program is set up to reauthenticate if it receives HTTP 401 from Steam Community. The assumption is the token is no longer valid, and a new one is required. Unfortunately, Steam Community doesn't always produce correct statuses when it's down, so sometimes it could reply unauthorized even though the token is still valid.

The program uses the Steam Community website exclusively for simplicity, so if the web login isn't working, the program can't log in.

**Comment by roughnecks** [comment]
Alright, thanks for the explanation.
