### ISSUE TITLE
Using Steam Browser Protocol for Links

### ISSUE THREAD

**Issue by RedMser** [GMMan/SteamNotificationsTray#4]
Right now, opening any of the notifications launches your browser with the correct page.
However, you could use [Steam's Browser Protocol](https://developer.valvesoftware.com/wiki/Steam_browser_protocol) to launch those pages directly inside of Steam's browser - most likely as an option inside of the settings.

The linked page is a bit out of date, but launching Steam with the parameter `-console` (or using the link steam://open/console) and opening any notifications tab shows you the internal names:

- Comments: [steam://url/CommentNotifications](steam://url/CommentNotifications)
- Invites: [steam://url/SteamIDInvitesPage](steam://url/SteamIDInvitesPage)
- New Items: [steam://url/CommunityInventory](steam://url/CommunityInventory)
- Gifts: [steam://url/ManageGiftsPage](steam://url/ManageGiftsPage)

If you wish to try them, I believe using Process.Start would make it work as expected.

I was unable to test the remaining ones since I do not have new notifications for them as of now, nor any easy way to get them, but you will probably figure out the rest!

**Comment by GMMan** [comment]
The option's disabled by default since I prefer the browser, but it's easy to enable.
