### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by roughnecks** [GMMan/SteamNotificationsTray#6]
Hi,
Is there a way to keep credentials saved when updating to a new release?

Thanks

**Comment by GMMan** [comment]
It should be carried forward since the last couple of releases.

**Comment by roughnecks** [comment]
Alright, thanks. I only extracted the exe and dlls and it worked.
Can I always keep exe.config or it should be replaced at given time?

**Comment by GMMan** [comment]
You should replace the .config, because it may contain new settings.

**Comment by roughnecks** [comment]
OK, done that 👍 
Have a nice one!
